data southentrance;
infile 'c:\MyRawData\South.dat';
input Entrance $ PassNumber PartySize Age;
proc print data = southentrance;
title 'South Entrance Data';
run;
data northentrance;
infile 'c:\MyRawData\North.dat';
input Entrance $ PassNumber PartySize Age Lot;
proc print data = northentrance;
title 'North Entrance Data';
run;
* Create a data set, both, combining northentrance and southentrance;
* Create a variable, AmountPaid, based on value of variable Age;
data bothentrance;
set southentrance northentrance;
if Age =. then AmountPaid =.;
else if Age < 3 then AmountPaid = 0;
else if Age < 65 then AmountPaid = 35;
else AmountPaid = 27;
run;
proc print data = bothentrance;
title 'Both Entrances';
run;
