data regular;
infile 'c:\MyRawData\Shoe.dat';
input Style $ 1-15 ExerciseType $ RegularPrice;
run;
proc sort data = regular;
by ExerciseType;
run;
data discount;
infile 'c:\MyRawData\Disc.dat';
input ExerciseType $ Adjustment;
run;
* Perform many-to-one match merge;
data prices;
merge regular discount;
by ExerciseType;
NewPrice = ROUND(RegularPrice - (RegularPrice * Adjustment),.01);
run;
proc print data = prices;
title 'Price List for May';
run;
