data heights;
infile 'c:\MyRawData\GirlHeights.dat';
input Region $ Height @@;
run;
* Use ANOVA to run one-way analysis of variance;
proc anova data = heights;
class Region;
model Height = Region;
means Region / DUNCAN;
means Region / LSD CLM CLDIFF;
title "Girls' Heights from Four Regions";
run;
